# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - run: | 
          ACTIONS_STEP_DEBUG=true
          echo "test"
          curl google.com

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          less $GITHUB_STEP_SUMMARY
          echo "-----------------------------------------------------------------------"
          gh run view $GITHUB_RUN_ID --repo $GITHUB_REPOSITORY --log
          echo Add other actions to build,
          echo test, and deploy your project.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
